application: coe2043-team-16
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css

- url: /.*
  script: moduleIII.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
